name: Publish to NPM
on: 
  release:
    types:
      - published
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      # - name: update changelog.txt
      #   run: |
      #     echo "★ Release Notes: $(date +%Y-%m-%d) ★\n≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡\n\nThanks for upgrading to the latest version of the ALKS CLI!\n\n${{ github.event.release.body }}\n\nHave feedback? https://github.com/Cox-Automotive/ALKS-CLI/issues" > changelog.txt
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
